import Head from 'next/head'
import Banner from '../components/banner'
import Footer from '../components/footer'

import Headers from '../components/header'
import Info from '../components/info'
import Popular from '../components/popular'
import Products from '../components/products'
import Testimonials from '../components/testimonials'

export default function Home() {
  return (
    <div className='bg-slate-50'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Headers />

      <main>
        <Banner />
        <Products />
        <Info />
        <Testimonials />
        <Popular />
      </main>

      <Footer />
    </div>
  )
}
