import Head from 'next/head'
import Banner from '../components/banner'

import Headers from '../components/header'


export default function Home() {
  return (
    <div className='bg-slate-50'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Headers />

      <main>
        <Banner />
      </main>

      <footer>
        footer
      </footer>
    </div>
  )
}
