import Head from 'next/head'
import Banner from '../components/banner'
import Info from '../components/info'
import { DefaultLayout } from '../components/layouts'
import Popular from '../components/popular'
import Products from '../components/products'
import Testimonials from '../components/testimonials'

export default function Home() {
  return (
    <div className='bg-slate-50'>
      <main>
        <Banner />
        <Products />
        <Info />
        <Testimonials />
        <Popular />
      </main>
    </div>
  )
}

Home.getLayout = function getLayout(page) {
  return (
    <DefaultLayout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {page}
    </DefaultLayout>
  )
}
